import { ChangeEventHandler, FocusEventHandler, KeyboardEventHandler, MouseEventHandler, ReactNode } from "react";
type InputProps = {
    "aria-describedby"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    autoComplete?: string;
    autoFocus?: boolean;
    className?: string;
    defaultValue?: string | number | readonly string[];
    disabled?: boolean;
    id?: string;
    name?: string;
    placeholder?: string;
    readOnly?: boolean;
    required?: boolean;
    value?: string | number | readonly string[];
    type?: string;
    error?: boolean;
    multiline?: boolean;
    rows?: number;
    startAdornment?: ReactNode;
    endAdornment?: ReactNode;
    variant?: "outlined" | "filled";
    darkMode?: boolean;
    onClick?: MouseEventHandler<HTMLInputElement | HTMLTextAreaElement>;
    onChange?: ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement>;
    onKeyDown?: KeyboardEventHandler<HTMLInputElement | HTMLTextAreaElement>;
    onKeyUp?: KeyboardEventHandler<HTMLInputElement | HTMLTextAreaElement>;
    onFocus?: FocusEventHandler<HTMLInputElement | HTMLTextAreaElement>;
    onBlur?: FocusEventHandler<HTMLInputElement | HTMLTextAreaElement>;
};
export declare const Input: import("react").ForwardRefExoticComponent<InputProps & import("react").RefAttributes<HTMLDivElement>>;
export {};
