name: Deploy OptiUI Docs to GitHub Pages

on:
  push:
    paths:
      - 'packages/docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies for docs package
        run: npm install --workspace=packages/docs

      - name: Build Next.js docs package
        run: npm run build --workspace=packages/docs

      - name: Export Next.js build output
        run: npm run export --workspace=packages/docs

      - name: Move export output to GitHub Pages directory
        run: |
          mkdir -p public-docs
          cp -r packages/docs/out/* public-docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-docs
          deploy_prefix: opti-ui-docs