name: Automating Publish to NPM

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish core package to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with sparse checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/core
          sparse-checkout-cone-mode: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies (only for core)
        working-directory: packages/core
        run: npm install

      - name: Build core package
        working-directory: packages/core
        run: npm run build

      - name: Publish to NPM
        working-directory: packages/core
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PUBLISH_KEY_NPM }}
